---
- hosts: amibuilder
  connection: local
  gather_facts: no

  vars_files:
    - ../generated/vars.yml
    - ../generated/vpc_settings.yml

  tasks:

    - name: Launch server
      ec2:
        region: "{{region}}"
        vpc_subnet_id: "{{ vpc_subnets|random }}"
        assign_public_ip: yes
        image: "{{server_image_id}}"
        key_name: "{{key_name}}"
        group: "{{project_name}}}"
        instance_type: t2.small
        instance_profile_name: "{{instance_iam}}"
        user-data: "{{ lookup('template', './templates/user-data.txt.j2') }}"
        exact_count: 1
        count_tag: "group"
        instance_tags:
          - group: "{{project_name}}"
        wait: true
      register: ec2
