- name: "Create ELB"
  local_action:
    module: ec2_elb_lb
    name: "{{elb_name}}"
    state: present
    connection_draining_timeout: 60
    cross_az_load_balancing: "yes"
    region: "{{region}}"
    subnets: "{{vpc_subnets}}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 8080
    security_group_ids:
      - "{{sg.group_id}}"
      - "{{elb_sg.group_id}}"
    health_check:
      ping_protocol: http # options are http, https, ssl, tcp
      ping_port: 8080
      ping_path: "/h" # not required for tcp or ssl
      response_timeout: 5 # seconds
      interval: 30 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 5
  tags: elb
