- name: Create key pair
  local_action:
    module: ec2_key
    region: "{{region}}"
    name: "{{private_key}}"
  register: result

- name: Ensure private key file exists locally
  local_action: 
    module: copy 
    content: "{{ result.key.private_key }}"
    dest: "../generated/{{ region }}-{{ private_key }}.pem"
    mode: 0400
