- hosts: amibuilder
  connection: local
  gather_facts: no

  vars_files:
    - generated/vars.yml
    - generated/vpc_settings.yml
  
  tasks:
  - name: launch temporary instance
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ private_key }}"
      group: "{{ project_name }}"
      instance_type: c3.2xlarge
      vpc_subnet_id: "{{ vpc_subnets|random }}"
      image: "{{ base_ami }}"
      wait: yes
      wait_timeout: 500
      exact_count: 1
      count_tag:
         Name: "{{project_name}}Baker"
         Role: ami_builder
      instance_tags:
         Name: "{{project_name}}Baker"
         Role: ami_builder
    register: ami_instance

  - name: Tag instance
    ec2_tag: 
      resource: "{{ami_instance.tagged_instances.0.id}}"
      region: "{{region}}" 
      state: present
      tags:
        Name: "{{project_name}}Baker"
        Role: ami_builder

  - name: waiting for ssh to start
    wait_for: port=22 host={{ ami_instance.tagged_instances.0.public_ip }} timeout=300
              search_regex=OpenSSH

  - name: add host to group
    add_host: name={{ ami_instance.tagged_instances.0.public_ip }} groups=just_created