---
#
# Configure VPC, Security group(s)
#
#
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:

    - name: "Create key pair for project"
      include: tasks/key_create.yml

    - name: "Create VPC for project"
      include: tasks/vpc_create.yml

    - name: "Create S3 bucket {{project_s3_bucket}} for {{project_name}}"
      local_action:
        module: s3
        bucket: "{{project_s3_bucket}}"
        mode: create
        region: "{{region}}"

    - name: Configure security groups
      local_action:
        module: ec2_group
        name: "{{project_name}}"
        description: "{{project_name}} game server security group"
        vpc_id: "{{vpc.vpc_id}}"
        region: "{{region}}"
        purge_rules: true
        # write you
        rules:
          # SSH
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          # http
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # Websocket (used by the game client)
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

   
