---
#
# Configure VPC, Security group(s)
#
#
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:

    - name: Create VPC
      local_action:
        module: ec2_vpc
        state: present
        cidr_block: 172.23.0.0/16
        resource_tags: { "Name":"{{project_name}}" }
        region: "{{region}}"
        internet_gateway: true
        subnets:
          - cidr: 172.23.1.0/24
            resource_tags: { "Name":"{{project_name}}-1" }
        subnets:
          - cidr: 172.23.2.0/24
            resource_tags: { "Name":"{{project_name}}-2" }
        subnets:
          - cidr: 172.23.3.0/24
            resource_tags: { "Name":"{{project_name}}-3" }
      register: vpc

    - name: Persist VPC Config
      template: src=templates/vpc_setup.j2 dest="./vpc_settings.yml"
      when: "vpc.changed"

    - name: Create key pair
      local_action:
        module: ec2_key
        region: "{{region}}"
        name: "{{private_key}}"
      register: result

    - name: Ensure private key file exists locally
      local_action: 
        module: copy 
        content: "{{ result.key.private_key }}"
        dest: "./{{ region }}-{{ private_key }}.pem"
        mode: 0400
      when: "result.changed"

    - name: "Create S3 bucket {{project_s3_bucket}} for {{project_name}}"
      local_action:
        module: s3
        bucket: "{{project_s3_bucket}}"
        mode: create
        region: "{{region}}"

    - name: Configure security groups
      local_action:
        module: ec2_group
        name: "{{project_name}}"
        description: "{{project_name}} game server security group"
        vpc_id: "{{vpc.vpc_id}}"
        region: "{{region}}"
        purge_rules: true
        # write you
        rules:
          # SSH
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          # http
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # Websocket (used by the game client)
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

   
