---
#
# Teardown security group(s) 
#
#
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml
    - vpc_settings.yml

  tasks:

    - name: Drop security groups
      local_action:
        module: ec2_group
        name: "{{project_name}}"
        description: "{{project_name}} game server security group"
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        state: absent

    - name: Drop VPC
      local_action:
        module: ec2_vpc
        region: "{{region}}"
        resource_tags: { "Name":"{{project_name}}" }
        state: absent
        vpc_id: "{{vpc_id}}"

    - name: Delete key pair
      local_action:
        module: ec2_key
        region: "{{region}}"
        name: "{{private_key}}"
        state: absent
