- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: "Drop role from {{item}}InstanceProfile"
      local_action:
        region: "us-east-1"
        module: aws_iam_instance_profile_role
        profile_name: "{{item}}InstanceProfile"
        role_name: "{{item}}"
        state: absent
      with_items:
        - "{{baker_iam}}"
        - "{{instance_iam}}"
    - name: "Drop instance profile {{item}}"
      local_action:
        region: "us-east-1"
        module: aws_iam_instance_profile
        profile_name: "{{item}}InstanceProfile"
        state: absent
      with_items:
        - "{{baker_iam}}"
        - "{{instance_iam}}"
    - name: "Drop policy {{item}}-EC2-Permissions"
      local_action:
        module: aws_iam_role_policy
        region: "us-east-1"
        role_name: "{{item}}"
        policy_name: "{{item}}-EC2-Permissions"
        state: absent
      with_items:
        - "{{baker_iam}}"
        - "{{instance_iam}}"
    - name: "Drop IAM role"
      local_action:
        region: "us-east-1"
        module: aws_iam_role
        role_name: "{{item}}"
        state: absent
      with_items:
        - "{{baker_iam}}"
        - "{{instance_iam}}"